function drawLeitura(d,h){var dma=new Array(3);dma=dat[d].split("-");var dt=new Date(dat[d]);var dsem=dt.getDay();var pp=dir=mt=0;var vv="";var smt="";var strUnid,hh,sh,mm,hms;ctxBoia.fillStyle="#ccc";ctxBoia.fillRect(10,28,420,25);ctxBoia.fillStyle="#eee";ctxBoia.fillRect(10,53,420,58);ctxBoia.fillStyle="#000";ctxBoia.font="18px verdana";if(((temDadosHoje&&d==0)||(!temDadosHoje&&d==1))&&h==0)ctxBoia.fillText(ltsRdg+":",15,47);ctxBoia.fillStyle="#900";hms=horaBoia[d][h].split(":");hh=parseInt(hms[0]);mm=hms[1];if(idioma==1){ctxBoia.fillText(nomeMes[Math.floor(dma[1])]+"/"+dma[2],170,47);if(hh==0){ctxBoia.fillText("12:"+mm+" am",330,47);}else if(hh==12){ctxBoia.fillText("12:"+mm+" pm",330,47);}else if(hh>12){sh=String(hh-12);if(hh<22)sh="0"+sh;ctxBoia.fillText(sh+":"+mm+" pm",330,47);}else{sh=String(hh);if(hh<10)sh="0"+sh;ctxBoia.fillText(sh+":"+mm+" am",330,47);}}else{ctxBoia.fillText(dma[2]+"/"+nomeMes[Math.floor(dma[1])],170,47);ctxBoia.fillText(String(hh)+":"+mm+" h",330,47);}
ctxBoia.fillText("("+nomeDiaSem[dsem]+")",250,47);if(temDir||temDirVento){drawRosa();}
ctxBoia.font="18px verdana";ctxBoia.fillStyle="#090";ctxBoia.fillText(wvs+":",15,75);ctxBoia.font="20px verdana";ctxBoia.fillStyle="#090";if(unidadeAltura=='f'){strUnid="ft ";}else{strUnid="m ";}
ctxBoia.fillText("        "+strUnid+"|     s |       \u00b0",15,97);ctxBoia.font="22px verdana";if(!isNaN(alturaSig[d][h])){hs=parseFloat(alturaSig[d][h]);if(unidadeAltura=='f'){hs=Math.round(hs*32.8)/10;}
aa=String(hs);if(idioma==0)aa=aa.replace(".",",");if(aa.length<3)aa=aa+",0";ctxBoia.fillText(aa,20,102);}else{ctxBoia.fillText("-",20,102);}
if(periodoBoia[d][h]!=""&&!isNaN(periodoBoia[d][h])){pp=Math.floor(periodoBoia[d][h]);if(pp>25)pp=Math.round(pp/10);ctxBoia.fillText(pp,105,102);}else{ctxBoia.fillText(" - ",110,102);}
vv=direcaoOndas[d][h];if(!isNaN(vv)){while(vv.length<3)vv="0"+vv;ctxBoia.fillText(vv,170,102);if(temDir){ctxBoia.font="12px verdana";ctxBoia.fillStyle="#000";dir=Math.floor((Math.floor(direcaoOndas[d][h])+11.2)/22.5);ctxBoia.fillText(direcoes_graficos_extenso[dir],100,73);drawSetaOndas(Math.floor(direcaoOndas[d][h]));}}
if(temVento){ctxBoia.fillStyle="#33d";ctxBoia.font="18px verdana";ctxBoia.fillText(wnd2+":",250,75);ctxBoia.font="20px verdana";ctxBoia.font="22px verdana";vv=parseInt(vento[d][h]);if(idUnidVento>0){vv=parseInt(unidadesRazao[unid_vento]*vv);unid=unidadesVentoSigla[idUnidVento];}else{unid=unidadesVentoSigla[0];}
ctxBoia.fillText(vv+unid,250,102);vv=ventoDir[d][h];if(vv!=""&&!isNaN(vv)){while(vv.length<3)vv="0"+vv;ctxBoia.fillText(vv,345,102);if(temDirVento){ctxBoia.fillStyle="#000";ctxBoia.font="12px verdana";dir=Math.floor((Math.floor(ventoDir[d][h])+11.2)/22.5);ctxBoia.fillText(direcoes_graficos_extenso[dir],315,73);drawSetaVento(Math.floor(ventoDir[d][h]));}}else{ctxBoia.fillText("-",345,102);}}else if(temTemp){ctxBoia.fillStyle="#d33";ctxBoia.font="18px verdana";ctxBoia.fillText(tmpr+":",235,75);ctxBoia.font="14px verdana";ctxBoia.fillText(stmp,235,97);ctxBoia.font="16px verdana";if(martemp[d][h]!=""&&!isNaN(martemp[d][h])){if(unidadeTemperatura=='f')mt=Math.round(10*(9*martemp[d][h]/5+32))/10;else mt=Math.round(10*martemp[d][h])/10;smt=String(mt);if(smt.length<3)smt=smt+".0";if(idioma==0)smt=smt.replace(".",",");ctxBoia.fillText(smt+"\u00b0"+unidadeTemperatura.toUpperCase(),278,100);}else{ctxBoia.fillText(" - ",278,100);}
if(artemp[d][h]!=""&&!isNaN(artemp[d][h])){if(unidadeTemperatura=='f')mt=Math.round(10*(9*artemp[d][h]/5+32))/10;else mt=Math.round(10*artemp[d][h])/10;smt=String(mt);if(smt.length<3)smt=smt+".0";if(idioma==0)smt=smt.replace(".",",");ctxBoia.font="14px verdana";ctxBoia.fillText(air,345,97);ctxBoia.font="16px verdana";ctxBoia.fillText(smt+"\u00b0"+unidadeTemperatura.toUpperCase(),368,100);}}}
function drawTitulo(){ctxBoia.font="18px verdana";linkText=nome+" ("+idBoia+") "+desc;linkWidth=ctxBoia.measureText(linkText).width;ctxBoia.fillStyle="#000";ctxBoia.fillText(linkText,10,20);canvasBoia.addEventListener("mousemove",on_mousemove_Boia,false);canvasBoia.addEventListener("click",on_click_Boia,false);}
function on_mousemove_Boia(ev){var x=y=d=h=0;x=relX_boia;y=relY_boia;if(temOndas){if(x>gx-4&&x<(gx+403)&&y<gy&&y>(gy-100)){graficoLink=-1;document.body.style.cursor="";for(dd=0;dd<2;dd++){for(cc=0;cc<25;cc++){if(xBotao[cc+25*dd]>=0&&x>=xBotao[cc+25*dd]&&x<=xBotao[cc+25*dd]+10){document.body.style.cursor="pointer";graficoLink=cc+25*dd;break;}}
if(graficoLink>=0)break;}
if(graficoLink<0){document.body.style.cursor="";}
else{if(graficoLink>24){d=1;h=graficoLink-25;}else{d=0;h=graficoLink;}
drawLeitura(d,h);}}else if(x>=linkXini&&x<=(linkXini+linkWidth)&&y<=linkYini&&y>=(linkYini-linkHeight)){document.body.style.cursor="pointer";inLink=true;}
else{if(temDadosHoje)drawLeitura(0,0);else drawLeitura(1,0);document.body.style.cursor="";inLink=false;}}else{document.body.style.cursor="";}}
function on_click_Boia(e){if(inLink){window.open(site,'_blank');}}
function drawRosa(){ctxBoia.clearRect(cxBoia-(raioRosaBoia+10),cyBoia-(raioRosaBoia+25),2*(raioRosaBoia+23),2*(raioRosaBoia+23));ctxBoia.lineWidth=1;ctxBoia.beginPath();ctxBoia.strokeStyle="#bbb";ctxBoia.moveTo(cxBoia+(raioRosaBoia+2)*Math.cos(45*Math.PI/180),cyBoia-(raioRosaBoia+2)*Math.sin(45*Math.PI/180));ctxBoia.lineTo(cxBoia+(raioRosaBoia+2)*Math.cos(225*Math.PI/180),cyBoia-(raioRosaBoia+2)*Math.sin(225*Math.PI/180));ctxBoia.moveTo(cxBoia+(raioRosaBoia+2)*Math.cos(135*Math.PI/180),cyBoia-(raioRosaBoia+2)*Math.sin(135*Math.PI/180));ctxBoia.lineTo(cxBoia+(raioRosaBoia+2)*Math.cos(315*Math.PI/180),cyBoia-(raioRosaBoia+2)*Math.sin(315*Math.PI/180));ctxBoia.stroke();ctxBoia.beginPath();ctxBoia.strokeStyle="#666";ctxBoia.moveTo(cxBoia-(raioRosaBoia+10),cyBoia);ctxBoia.lineTo(cxBoia+(raioRosaBoia+10),cyBoia);ctxBoia.moveTo(cxBoia,cyBoia-(raioRosaBoia+10));ctxBoia.lineTo(cxBoia,cyBoia+(raioRosaBoia+10));ctxBoia.moveTo(cxBoia+raioRosaBoia,cyBoia);ctxBoia.strokeStyle="#000";ctxBoia.arc(cxBoia,cyBoia,raioRosaBoia,0,2*Math.PI,true);ctxBoia.stroke();ctxBoia.beginPath();ctxBoia.arc(cxBoia,cyBoia,3,0,2*Math.PI,true);ctxBoia.fill();ctxBoia.strokeStyle="#888";ctxBoia.lineWidth=3;for(var c=1;c<72;c+=2){ctxBoia.moveTo(cxBoia+(raioRosaBoia+2)*Math.cos(5*c*Math.PI/180),cyBoia-(raioRosaBoia+2)*Math.sin(5*c*Math.PI/180));ctxBoia.arc(cxBoia,cyBoia,(raioRosaBoia+2),-5*c*Math.PI/180,-5*(c+1)*Math.PI/180,true);}
ctxBoia.stroke();ctxBoia.font="18px verdana";ctxBoia.fillText("N",cxBoia-6,cyBoia-(raioRosaBoia+12));ctxBoia.font="14px arial";ctxBoia.fillText("E",cxBoia+(raioRosaBoia+10),cyBoia+5);ctxBoia.fillText("S",cxBoia-5,cyBoia+(raioRosaBoia+22));if(!desenhaO){ctxBoia.fillText("O",cxBoia-(raioRosaBoia+22),cyBoia+5);desenhaO=true;}
ctxBoia.font="12px arial";ctxBoia.fillStyle="#888";ctxBoia.fillText("NE",cxBoia+(raioRosaBoia+4)*Math.cos(45*Math.PI/180),cyBoia-(raioRosaBoia+4)*Math.sin(45*Math.PI/180));ctxBoia.fillText(sW,cxBoia+(raioRosaBoia+23)*Math.cos(223*Math.PI/180),cyBoia-(raioRosaBoia+23)*Math.sin(223*Math.PI/180));ctxBoia.fillText("SE",cxBoia+(raioRosaBoia+10)*Math.cos(310*Math.PI/180),cyBoia-(raioRosaBoia+10)*Math.sin(310*Math.PI/180));ctxBoia.fillText(nW,cxBoia+(raioRosaBoia+17)*Math.cos(142*Math.PI/180),cyBoia-(raioRosaBoia+17)*Math.sin(142*Math.PI/180));}
function drawRosaApagada(){ctxBoia.beginPath();ctxBoia.beginPath();ctxBoia.strokeStyle="#ccc";ctxBoia.fillStyle="#ccc";ctxBoia.moveTo(cxBoia-(raioRosaBoia+10),cyBoia);ctxBoia.lineTo(cxBoia+(raioRosaBoia+10),cyBoia);ctxBoia.moveTo(cxBoia,cyBoia-(raioRosaBoia+10));ctxBoia.lineTo(cxBoia,cyBoia+(raioRosaBoia+10));ctxBoia.moveTo(cxBoia+raioRosaBoia,cyBoia);ctxBoia.arc(cxBoia,cyBoia,raioRosaBoia,0,2*Math.PI,true);ctxBoia.stroke();ctxBoia.font="18px verdana";ctxBoia.fillText("N",cxBoia-6,cyBoia-(raioRosaBoia+12));}
function drawSetasLegenda(){var x=y=0;x=cxBoia-(Math.floor((raioRosaBoia+15)/2));y=cyBoia+(raioRosaBoia+55);ctxBoia.font="12px verdana";ctxBoia.fillStyle="#000";ctxBoia.fillText(drc+":",x-(Math.floor((raioRosaBoia-5)/2)),y-22);ctxBoia.font="14px verdana";if(temDir){ctxBoia.fillStyle="#090";ctxBoia.fillText(wvs,x-(Math.floor((raioRosaBoia-5)/2)),y-7);ctxBoia.beginPath();ctxBoia.moveTo(x,y);ctxBoia.lineTo(x,y-4);ctxBoia.lineTo(x+20,y-4);ctxBoia.lineTo(x+20,y-8);ctxBoia.lineTo(x+(Math.floor((raioRosaBoia+15)/2)),y);ctxBoia.lineTo(x+20,y+8);ctxBoia.lineTo(x+20,y+4);ctxBoia.lineTo(x,y+4);ctxBoia.fill();}
if(temDirVento){if(temDir)x=cxBoia+30;ctxBoia.fillStyle="#33d";ctxBoia.fillText(wnd2,x-23,y-7);ctxBoia.beginPath();ctxBoia.moveTo(x,y);ctxBoia.lineTo(x,y-2);ctxBoia.lineTo(x+20,y-2);ctxBoia.lineTo(x+20,y-8);ctxBoia.lineTo(x+(Math.floor((raioRosaBoia+15)/2)),y);ctxBoia.lineTo(x+20,y+8);ctxBoia.lineTo(x+20,y+2);ctxBoia.lineTo(x,y+2);ctxBoia.fill();}}
function drawSetaVento(ang){var x=cxBoia;var y=cyBoia-(raioRosaBoia-2);var w=10;var h=130;ctxBoia.save();ctxBoia.translate(cxBoia,cyBoia);ctxBoia.rotate((Math.PI/180)*ang);ctxBoia.translate(-cxBoia,-cyBoia);ctxBoia.beginPath();ctxBoia.moveTo(x-2,y);ctxBoia.lineTo(x+2,y);ctxBoia.lineTo(x+2,y+(Math.floor((raioRosaBoia+15)/2)));ctxBoia.lineTo(x+8,y+(Math.floor((raioRosaBoia+15)/2)));ctxBoia.lineTo(x,y+(raioRosaBoia-5));ctxBoia.lineTo(x-8,y+(Math.floor((raioRosaBoia+15)/2)));ctxBoia.lineTo(x-2,y+(Math.floor((raioRosaBoia+15)/2)));ctxBoia.lineTo(x-2,y);ctxBoia.fillStyle="#33d";ctxBoia.fill();ctxBoia.translate(cxBoia,cyBoia);ctxBoia.rotate((Math.PI/180)*-ang);ctxBoia.translate(-cxBoia,-cyBoia);}
function drawSetaOndas(ang){var x=cxBoia;var y=cyBoia-(raioRosaBoia-2);var w=10;var h=130;ctxBoia.save();ctxBoia.translate(cxBoia,cyBoia);ctxBoia.rotate((Math.PI/180)*ang);ctxBoia.translate(-cxBoia,-cyBoia);ctxBoia.beginPath();ctxBoia.moveTo(x-4,y);ctxBoia.lineTo(x+4,y);ctxBoia.lineTo(x+4,y+(Math.floor((raioRosaBoia+15)/2)));ctxBoia.lineTo(x+10,y+(Math.floor((raioRosaBoia+15)/2)));ctxBoia.lineTo(x,y+(raioRosaBoia-5));ctxBoia.lineTo(x-10,y+(Math.floor((raioRosaBoia+15)/2)));ctxBoia.lineTo(x-4,y+(Math.floor((raioRosaBoia+15)/2)));ctxBoia.lineTo(x-4,y);ctxBoia.fillStyle="#090";ctxBoia.fill();ctxBoia.translate(cxBoia,cyBoia);ctxBoia.rotate((Math.PI/180)*-ang);ctxBoia.translate(-cxBoia,-cyBoia);}
boiaCarregada=false;function lerBoia(){if(!boiaCarregada){canvasBoia=document.getElementById('quadroBoia');ctxBoia=canvasBoia.getContext('2d');if(boia.indexOf("|")>0){boias=boia.split("|");$("#menu_boias").show();for(var i=0;i<boias.length;i++){if(i>1){$('#boia'+String(i-1)).after($('#boia1').clone().attr("id","boia"+i));$('#boia'+i+' a').attr("href","javascript:mostraBoia("+i+");");}
$("#boia"+i+" a").html(boias[i]);};}else{boias[0]=boia;}
mostraBoia(0);boiaCarregada=true;}}
nrBoia=-1;function mostraBoia(id){nrBoia=id;idBoia=boias[id];ctxBoia.clearRect(0,0,650,250);ctxBoia.fillStyle="#00c";ctxBoia.font="38px verdana";ctxBoia.fillText(waitData,40,125);lerJsonBoia();if(boias.length>1){$('#menu_boias .abas_graficos li').each(function(){$(this)[0].className="normal";});$('#boia'+id)[0].className="ativa";}}
function limpaDados(){temVento=false;temOndas=false;temTemp=false;temDir=false;temDirVento=false;temDadosHoje=false;hmax=0.0;vmax=0;tmax=0;nome="";statusBoia="";site="";desc="";linkWidth=0;linkHeight=30;linkXini=10;linkYini=30;for(var dd=0;dd<2;dd++){horaBoia[dd]=new Array(25);alturaSig[dd]=new Array(25);alturaMax[dd]=new Array(25);periodoBoia[dd]=new Array(25);direcaoOndas[dd]=new Array(25);vento[dd]=new Array(25);ventoDir[dd]=new Array(25);rajada[dd]=new Array(25);pressao[dd]=new Array(25);artemp[dd]=new Array(25);martemp[dd]=new Array(25);dat[dd]="";for(cc=0;cc<25;cc++){horaBoia[dd][cc]="";alturaSig[dd][cc]="";alturaMax[dd][cc]="";periodoBoia[dd][cc]="";direcaoOndas[dd][cc]="";vento[dd][cc]="";ventoDir[dd][cc]="";rajada[dd][cc]="";pressao[dd][cc]="";artemp[dd][cc]="";martemp[dd][cc]="";xBotao[cc]=0;xBotao[cc+25]=0;}}}
function lerJsonBoia(){var dd=-1,cc=-1;var hh="";var alt=0;limpaDados();$.getJSON('/boias/dados?id='+idBoia,function(data){nome=data.nome;statusBoia=data.status;site=data.site;descricao=data.descricao;tipoBoia=parseInt(data.tipo);dd=-1;if(tipoBoia==3){$('#siteBoia a').attr("href",site).html("<strong>"+nome+"</strong> ("+xtrnal+")");$('#quadroBoia').hide();$('#areaBoia').attr("style","width:300px;height:80px;");$('#siteBoia').show();}else{$.each(data.diario,function(i,dadosDia){dd++;cc=0;dat[dd]=dadosDia.data;$.each(dadosDia.leituras,function(i,leituras){hh=leituras.hora;if(hh!="-"){horaBoia[dd][cc]=leituras.hora;alturaSig[dd][cc]=leituras.hs;alturaMax[dd][cc]=leituras.hmax;periodoBoia[dd][cc]=leituras.perPrim;direcaoOndas[dd][cc]=leituras.dirOnda;pressao[dd][cc]=leituras.pressao;artemp[dd][cc]=leituras.artemp;martemp[dd][cc]=leituras.martemp;if(dd==0)temDadosHoje=true;if(alturaSig[dd][cc]!=""&&!isNaN(alturaSig[dd][cc])){if(parseFloat(alturaSig[dd][cc])>0.0)cc++;}}});cc=0;if(!(typeof dadosDia.ventos=="undefined"||!(dadosDia.ventos instanceof Array))){$.each(dadosDia.ventos,function(i,ventos){hh=ventos.hora;if(hh!="-"){vento[dd][cc]=ventos.intVento;if(vento[dd][cc]!=""&&!isNaN(vento[dd][cc]))vento[dd][cc]=Math.round(1.9438*parseFloat(vento[dd][cc]));ventoDir[dd][cc]=ventos.dirVento;rajada[dd][cc]=ventos.rajada;if(vento[dd][cc]!=""&&!isNaN(vento[dd][cc])){if(parseFloat(vento[dd][cc])>0.0)cc++;}}});}});inicializaGraficos();}});}
var hMaxBoia=0.0;function inicializaGraficos(){hmax=0.0;vmax=0;if(statusBoia!=1&&boias.length==1){$("#btn-barra2").toggleClass("barra-fechada");$('#conteudo-box2').hide();$('#nome_boia').html(buoy+": "+boias[0]+" &nbsp; ( <b>"+statusTipo[statusBoia]+"</b> )");}
ctxBoia.clearRect(0,0,650,250);for(dd=0;dd<2;dd++){for(cc=0;cc<25;cc++){if(alturaSig[dd][cc]!=""&&!isNaN(alturaSig[dd][cc])){temOndas=true;if(parseFloat(alturaSig[dd][cc])>hmax)hmax=parseFloat(alturaSig[dd][cc]);if(direcaoOndas[dd][cc]!=""&&!isNaN(direcaoOndas[dd][cc]))temDir=true;}
if(vento[dd][cc]!=""&&!isNaN(vento[dd][cc])){temVento=true;if(vento[dd][cc]>vmax)vmax=vento[dd][cc];if(ventoDir[dd][cc]!=""&&!isNaN(ventoDir[dd][cc]))temDirVento=true;}
if(martemp[dd][cc]!=""&&!isNaN(martemp[dd][cc])){temTemp=true;if(martemp[dd][cc]>tmax)tmax=martemp[dd][cc];}}}
if(temOndas){if(!temDirVento&&!temDir)drawRosaApagada();hmax=Math.floor(hmax)+1.0;if(hmax<3.0)hmax=3.0;if(temVento){if(10*hmax>vmax){fatorBoia=(10/hmax);ymax=fatorBoia*hmax*10;}else{fatorBoia=(100/vmax);ymax=fatorBoia*vmax;}}else if(temTemp){tmax=Math.ceil(tmax/10)*10+5;if(10*hmax>tmax){fatorBoia=(10/hmax);ymax=fatorBoia*hmax*10;}else{fatorBoia=(100/tmax);ymax=fatorBoia*tmax;}}else{fatorBoia=(10/hmax);ymax=fatorBoia*hmax*10;}
drawTitulo();hMaxBoia=hmax;if(temDadosHoje)drawLeitura(0,0);else drawLeitura(1,0);plotaGraficoOndas();drawGrafico();if(temVento)plotaGraficoVento();drawEscala();if(temDir||temDirVento){drawSetasLegenda();}}else{ctxBoia.fillStyle="#900";ctxBoia.font="18px verdana";nomes=nome.split("-");ctxBoia.fillText(nomes[0],30,50);n1="";if(nomes[1]!=undefined)n1=nomes[1];ctxBoia.fillText(n1+" ("+idBoia+")",30,70);ctxBoia.fillText(desc,30,90);ctxBoia.font="38px verdana";ctxBoia.fillText(noWvDat,100,150);$('#conteudo-box2').hide();}}
function plotaGraficoOndas(){var hms=new Array(3);var pp=p=x=y=0;for(dd=0;dd<2;dd++){for(cc=0;cc<25;cc++){if(alturaSig[dd][cc]!=""&&!isNaN(alturaSig[dd][cc])){hms=horaBoia[dd][cc].split(":");x=gx+400-Math.round(200*(dd+(24-Math.floor(hms[0])-Math.floor(hms[1])/60)/24));y=gy-Math.round(alturaSig[dd][cc]*10*fatorBoia);if(periodoBoia[dd][cc]!=""&&!isNaN(periodoBoia[dd][cc])){pp=Math.floor(periodoBoia[dd][cc]);if(pp>25)pp=Math.round(pp/10);for(p=0;p<limitePeriodoBoia.length;p++){if(pp<=limitePeriodoBoia[p]){ctxBoia.fillStyle="#"+corPeriodo[p];break;}}}else{ctxBoia.fillStyle="#888";}
ctxBoia.fillRect(x-3,y,6,gy-y-1);xBotao[cc+25*dd]=x-5;}}}}
function plotaGraficoVento(){var hms=new Array(3);var x=y=x0=y0=h0=0;var cont=false;ctxBoia.fillStyle="#33d";ctxBoia.beginPath();ctxBoia.lineWidth=1;for(dd=0;dd<2;dd++){for(cc=0;cc<25;cc++){if(vento[dd][cc]!=""&&!isNaN(vento[dd][cc])){hms=horaBoia[dd][cc].split(":");x=gx+400-Math.round(200*(dd+(24-Math.floor(hms[0])-Math.floor(hms[1])/60)/24));y=gy-vento[dd][cc]*fatorBoia;ctxBoia.strokeStyle="#fff";ctxBoia.strokeRect(x-5,y-5,8,8);ctxBoia.fillRect(x-3,y-3,5,5);if(cont){if(!(h0>Math.floor(hms[0])+1||(h0<Math.floor(hms[0])&&h0>Math.floor(hms[0])-23))){ctxBoia.strokeStyle="#33d";ctxBoia.moveTo(x0,y0);ctxBoia.lineTo(x,y);}}
x0=x;y0=y;h0=Math.floor(hms[0]);cont=true;}else{cont=false;}}}
ctxBoia.stroke();}
function plotaGraficoTemp(){var hms=new Array(3);var x=y=x0=y0=h0=0;var cont=false;ctxBoia.fillStyle="#d33";ctxBoia.beginPath();ctxBoia.lineWidth=1;for(dd=0;dd<2;dd++){for(cc=0;cc<25;cc++){if(martemp[dd][cc]!=""&&!isNaN(martemp[dd][cc])){hms=horaBoia[dd][cc].split(":");x=gx+400-Math.round(200*(dd+(24-Math.floor(hms[0])-Math.floor(hms[1])/60)/24));y=gy-martemp[dd][cc]*fatorBoia;ctxBoia.strokeStyle="#fff";ctxBoia.strokeRect(x-5,y-5,8,8);ctxBoia.fillRect(x-3,y-3,5,5);if(cont){if(!(h0>Math.floor(hms[0])+1||(h0<Math.floor(hms[0])&&h0>Math.floor(hms[0])-23))){ctxBoia.strokeStyle="#009";ctxBoia.moveTo(x0,y0);ctxBoia.lineTo(x,y);ctxBoia.stroke();}}
x0=x;y0=y;h0=Math.floor(hms[0]);cont=true;}else{cont=false;}}}
ctxBoia.stroke();}
function drawGrafico(){var dt=new Date(dat[1]);var dsem=dt.getDay();var ontem=dsem;dsem++;if(dsem>6)dsem=0;var c=0;ctxBoia.beginPath();ctxBoia.strokeStyle="#000";ctxBoia.lineWidth=1;ctxBoia.moveTo(gx-3,gy);ctxBoia.lineTo(gx-3,gy-100);ctxBoia.moveTo(gx-3,gy);ctxBoia.lineTo(gx+403,gy);if(temVento||temTemp)ctxBoia.lineTo(gx+403,gy-100);ctxBoia.stroke();ctxBoia.strokeStyle="#666";ctxBoia.moveTo(gx+50,gy);ctxBoia.lineTo(gx+50,gy-5);ctxBoia.moveTo(gx+100,gy);ctxBoia.lineTo(gx+100,gy-5);ctxBoia.moveTo(gx+150,gy);ctxBoia.lineTo(gx+150,gy-5);ctxBoia.moveTo(gx+200,gy);ctxBoia.lineTo(gx+200,gy-5);ctxBoia.moveTo(gx+250,gy);ctxBoia.lineTo(gx+250,gy-5);ctxBoia.moveTo(gx+300,gy);ctxBoia.lineTo(gx+300,gy-5);ctxBoia.moveTo(gx+350,gy);ctxBoia.lineTo(gx+350,gy-5);ctxBoia.stroke();ctxBoia.font="10px verdana";ctxBoia.fillStyle="#777";ctxBoia.fillText(mdnt,gx-5,gy+10);ctxBoia.fillText(am6,gx+45,gy+10);ctxBoia.fillText(noon,gx+90,gy+10);ctxBoia.fillText(pm6,gx+140,gy+10);ctxBoia.fillText(mdnt,gx+195,gy+10);ctxBoia.fillText(am6,gx+245,gy+10);ctxBoia.fillText(noon,gx+290,gy+10);ctxBoia.fillText(pm6,gx+340,gy+10);ctxBoia.fillText(mdnt,gx+395,gy+10);ctxBoia.font="12px arial";ctxBoia.fillStyle="#777";ctxBoia.fillText(nomeDiaSem[ontem],gx+85,gy-95);ctxBoia.fillText(nomeDiaSem[dsem],gx+290,gy-95);var strUnid="m ";var fatorUnid=10;var altStep=1;if(unidadeAltura=='f'){fatorUnid=3.28;strUnid="ft";if(hMaxBoia>2)altStep=2;if(hMaxBoia>4)altStep=4;}
ctxBoia.fillStyle="#090";for(c=altStep;c<=100;c+=altStep){if(fatorUnid*fatorBoia*c<80){ctxBoia.fillText(c+",0",gx-23,gy-(fatorUnid*fatorBoia*c)+5);}else break;}
ctxBoia.fillText(strUnid,gx-20,gy-95);if(temVento){ctxBoia.fillStyle="#33d";for(c=10;c<=Math.floor(100/fatorBoia);c+=10){if(fatorBoia*c<100){ctxBoia.fillText(c,gx+405,gy-(fatorBoia*c)+5);}}
ctxBoia.fillText("kt",gx+407,gy-90);}else{ctxBoia.fillStyle="#090";for(c=altStep;c<=100;c+=altStep){if(fatorUnid*fatorBoia*c<80){ctxBoia.fillText(c+",0",gx+405,gy-(fatorUnid*fatorBoia*c)+5);}else break;}
ctxBoia.fillText(strUnid,gx+407,gy-95);}
ctxBoia.strokeStyle="#eee";var step=10;if(unidadeAltura=='f'){step=3.28;if(hMaxBoia>2)step=2*step;if(hMaxBoia>4)step=2*step;}
for(c=step;c<=ymax;c+=step){if(c*fatorBoia<80){ctxBoia.moveTo(gx-3,gy-c*fatorBoia);ctxBoia.lineTo(gx+400,gy-c*fatorBoia);}else break;}
ctxBoia.strokeStyle="#777";ctxBoia.moveTo(gx+200,gy);ctxBoia.lineTo(gx+200,gy-100);ctxBoia.stroke();}
function drawEscala(){var o=4;ctxBoia.font="10px verdana";ctxBoia.fillStyle="#000";ctxBoia.fillText(prd+" (s)",gx-15,gy+23);for(p=0;p<limitePeriodoBoia.length;p++){if(p>4)o=0;ctxBoia.fillStyle="#"+corPeriodo[p];ctxBoia.fillRect(gx+50+22*p,gy+13,22,13);if(p<2||p>limitePeriodoBoia.length-4)ctxBoia.fillStyle="#fff";else ctxBoia.fillStyle="#000";ctxBoia.fillText(limitePeriodoBoia[p],gx+53+o+22*p,gy+23);}}